### ISSUE TITLE
Request for sharing "netsim"  yaml configuration file for CUTS-PLUS?

### ISSUE THREAD

**Issue by SaqibMamoon** [jarrycyx/UNN#10]
Dear @jarrycyx 

Could you please share the yaml configuration file for "netsim"  experiment in CUTS-PLUS?

Because i'm facing the constant issue below, and i can't figure out why and how to resolve it.

`
graph = cuts_plus.main(data, mask, true_cm, sota_opt.cuts_plus, log, device=device)

UNN-main/CUTS_Plus/cuts_plus.py", line 395, in main  Graph = multicad.train(data, mask, data, true_cm)

UNN-main/CUTS_Plus/cuts_plus.py", line 305, in train y_pred, loss = self.latent_data_pred(x, y, mask_x, mask_y)

UNN-main/CUTS_Plus/cuts_plus.py", line 162, in latent_data_pred graph_sampled = sample_bernoulli(Graph, self.args.batch_size)

UNN-main/CUTS_Plus/cuts_plus.py", line 147, in sample_bernoulli return torch.bernoulli(sample_matrix).float()

RuntimeError: Expected p_in >= 0 && p_in <= 1 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
`
Thanks in advance!!

**Comment by jarrycyx** [comment]
Config file for netsim is in the following 

```

  dir_name: outputs
  task_name: netsim

  log:
    stdout: false
    stderr: false
    tensorboard: true
    
  data:
    name: netsim
    param:
      dataset_id: 2
    missing: 
      name: RBM
      params:
        p_block: 0
        p_noise: 0.1
        max_seq: 48
        min_seq: 12
    pre_impute:
      name: TimesNet
      params: 
        total_epoch: 10
        window_size: 24
    reduce_data: 1P
    seed: 0

  reproduc:
    seed: 42
    benchmark: false
    deterministic: true


  sota:

    cuts:
      # disable_graph: true

      n_nodes: auto
      input_step: 5
      batch_size: 128
      data_dim: 1
      total_epoch: 1000

      n_groups: 8
      group_policy: multiply_2_every_5

      supervision_policy: masked_before_600
      fill_policy: rate_0.01_after_200

      # supervision_policy: full
      # fill_policy: no_update

      # fill_policy: every_300

      show_graph_every: 200
      
      data_pred:
        model: multi_mlp
        pred_step: 1
        mlp_hid: 128
        mlp_layers: 3
        lr_data_start: 1e-4
        lr_data_end: 1e-5
        weight_decay: 0.001
        prob: true

      graph_discov:
        lambda_s_start: 5
        lambda_s_end: 5
        lr_graph_start: 1e-2
        lr_graph_end: 1e-3
        start_tau: 1
        end_tau: 0.1
        dynamic_sampling_milestones: [0]
        dynamic_sampling_periods: [1]

      causal_thres: value_0.5 # percentile_40

      
```

As for the error message, I am not quite sure about the reason. See if this config does not solve the problem.
