### ISSUE TITLE
netsim

### ISSUE THREAD

**Issue by Taleword2** [jarrycyx/UNN#7]
Can you provide yaml configuration files related to the "netsim" experiment in CUTS?

**Comment by jarrycyx** [comment]
```

dir_name: outputs
task_name: multi_cad_netsim

log:
  stdout: false
  stderr: false
  tensorboard: true
  
data:
  name: netsim
  param:
    dataset_id: 0
  pre_sample:
    random_missing:
      missing_var: all
      missing_prob: 0.1
      seed: 0
    # random_period: 
    #   choices: [1,2,3,4]
    #   prob: [0.4,0.3,0.2,0.1]
    #   seed: 3
    # random_period: 
    #   choices: [1]
    #   prob: [1]
    #   seed: 0

  # init_fill: linear
  init_fill: zoh

reproduc:
  seed: 42
  benchmark: false
  deterministic: true

multi_cad:
  # disable_graph: true

  n_nodes: 15
  input_step: 5
  batch_size: 128
  data_dim: 1
  total_epoch: 1000

  supervision_policy: masked_before_600
  fill_policy: rate_0.01_after_200

  # supervision_policy: full
  # fill_policy: no_update

  # fill_policy: every_300

  show_graph_every: 200
  
  data_pred:
    model: multi_mlp
    pred_step: 1
    mlp_hid: 128
    mlp_layers: 3
    lr_data_start: 1e-4
    lr_data_end: 1e-5
    weight_decay: 0.001
    prob: true

  graph_discov:
    lambda_s_start: 5
    lambda_s_end: 5
    lr_graph_start: 1e-2
    lr_graph_end: 1e-3
    start_tau: 1
    end_tau: 0.1
    dynamic_sampling_milestones: [0]
    dynamic_sampling_periods: [1]

  causal_thres: value_0.5 # percentile_40

sota:
  # neural_granger_causality:
  #   lam: 0.001
  #   lam_ridge: 1e-4
  #   lr: 5e-2
  #   penalty: H
  # pcmci:
  #   tau_max: 5
  #   pc_alpha: 0.05
  #   ci_test: CMIknn
    
```
